### ISSUE TITLE
Code Usage

### ISSUE THREAD

**Issue by Caraxi** [FoxShadow10/AutoEmotion#1]
I don't mind if you do or not, but some acknowledgement that you used my horrible code would be nice~

**Comment by FoxShadow10** [comment]
As soon as I get home I will add you to the creditis. I'm really sorry for forgetting, it wasn't intentional. 
And thank you so much for your work, I couldn't have done it without it.

**Comment by FoxShadow10** [comment]
Added, sorry again ♥
