### ISSUE TITLE
[Feature Request] Option to show/ignore Emote Log

### ISSUE THREAD

**Issue by MinoWizard** [FoxShadow10/AutoEmotion#2]
Basically, I'm requesting a plugin option for whether or not to show logged emotes in the chat window. For instance, /wave will display the message "You wave." in chat.

By default, AutoEmotion will display this Emote log in the chat window if the Emotes window has "Display log message." enabled. Ideally, I'd like it if AutoEmotion had its own setting for log messages so that automatic emotes don't trigger these messages while keeping "Display log message" on for manually activating emotes.

**Comment by FoxShadow10** [comment]
Got it! Currently testing a version with the toggle, will close the issue once the plugin is tested and updated

**Comment by FoxShadow10** [comment]
Released on version 1.1.0
