### ISSUE TITLE
[Feature Request / Bug Report(?)]

### ISSUE THREAD

**Issue by Xisyera** [FoxShadow10/AutoEmotion#5]
Hey hey! I really like this plugin! However, I've found a little issue! Sometimes, when you use it for the first time in a zone, the emote takes a few seconds to work. Afterwards, it works instantly.

I have no technical knowledge, however, I figured I'd just bring this to your attention!

Maybe adding a delay / timer feature for emotes would be cool too! That way you can time an emote perfectly with however you'd like it to work?

**Comment by FoxShadow10** [comment]
Hi, yes I noticed it too, a slowdown only on the first use of the plugin. I am investigating the issue.
